"""Add Team and Position

Revision ID: 3e3ba0bc2e75
Revises: d86d637641bd
Create Date: 2019-04-04 16:46:25.749096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3ba0bc2e75'
down_revision = 'd86d637641bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unbabelite', sa.Column('position', sa.String(), nullable=True))
    op.add_column('unbabelite', sa.Column('team', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unbabelite', 'team')
    op.drop_column('unbabelite', 'position')
    # ### end Alembic commands ###
